---
- name: Install Apache Web Server
  hosts: all
  become: yes

  tasks:
    - name: Update apt package
      apt:
       update_cache: yes
    
    - name: Install Apache
      apt: name=apache2 state=latest
    
    - name: Start Apache Service
      service: name=apache2 state=started enabled=yes
...
