---
- name: UN-Install Apache Web Server
  hosts: all
  become: yes  # Run tasks with sudo privileges

  vars:
    src_file: ./App/index.html
    dest_file: /var/www/html

  tasks:
    - name: Update apt package cache
      apt:  update_cache=yes

    - name: LS folder WWW
      shell: ls /var/www/
      register: ls_out

    - name: Print Result LS folder WWW
      debug:
        var: ls_out.stdout

    - name: LS folder HTML
      shell: ls /var/www/html
      register: ls_out

    - name: Print result LS folder HTML
      debug:
        var: ls_out.stdout

    - name: Delete Apache on Ubuntu
      apt:  name=apache2  state=absent
#      when: ansible_os_family == "Debian"

#    - name: Delete httpd on AWS
#      yum:  name=httpd  state=absent
#      when: ansible_os_family == "RedHat"

    - name: Delete Web File
      file: path={{  dest_file  }}   state=absent

    - name: LS folder WWW
      shell: ls /var/www/
      register: ls_out

    - name: Print Result LS folder WWW
      debug:
        var: ls_out.stdout