---
- name: Install Custom Apache Web Server with roles
  hosts: all
  become: yes  # Run tasks with sudo privileges
  
  roles:
    - { role: role1, --extra-var "NEW env", when: ansible_system == 'Linux' }
  