---
- name: Copy File to Hosts
  copy: src={{ src_file }} dest={{ dest_folder }}  mode=0555

- name: Print Loop Message
  debug:
    msg : "Hello {{ item }}"
  loop: "{{ message_loop }}"

- name: Print os_family of Host
  debug:
    var: ansible_facts.os_family

- name: Create Variable and Print it
  vars:
    my_var: "var created by ansible"
  debug:
     var: my_var

- name: Save host's ip address
  shell: echo {{ansible_default_ipv4.address }} > ~/log.txt 
  delegate_to: localhost
  become: no

- name: Reboot host
  reboot:

- name: print updtime
  shell: uptime -s >> ~/log.txt
  delegate_to: localhost
  become: no

