---
# tasks file for del_apache
- block:
  - name: Update apt package
    apt: update_cache=yes
    
  - name: Delete Apache
    apt: name=apache2 state=absent

  - name: Delete Web File
    file: path={{ dest_file }} state=absent

  when: ansible_os_family == "Debian"

- block:
  - name: Update yum package
    yum: update_cache=yes
    
  - name: Delete httpd
    yum: name=httpd state=absent
      
  - name: Delete Web File
    file: path={{ dest_file }} state=absent
      
  when: ansible_os_family == "RedHat"